Remove unnecessary CodeQL SARIF upload
It seems the github/codeql-action/analyze GHA takes care of uploading
the SARIF so we don't need to do it ourselves.

Trying to do so fails with:

  Error: Aborting upload: only one run of the codeql/analyze or
  codeql/upload-sarif actions is allowed per job per tool/category.

Signed-off-by: Daniel Farrell <dfarrell@redhat.com>